name: responsiveplus
description: ResponsivePlus is a powerful and versatile package designed to simplify and enhance responsive design in Flutter applications.
version: 1.0.3
homepage: https://rillastudios.ca/
repository: https://github.com/RillaStudios/responsiveplus
issue_tracker: https://github.com/RillaStudios/responsiveplus/issues
funding: [https://www.buymeacoffee.com/izaakford]

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
